Repository plugwise/plugwise_usb-beta, pull requests merged in 2023-12, with the labels that each got.

#106 Cachebump and remove black
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  scripts/core-testing.sh
Labels: bug, dependencies

#111 Backend update to v0.31.1
  CHANGELOG.md
  custom_components/plugwise_usb/manifest.json
Labels: enhancement

#112 Correct missing plugwise_usb parts
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  pyproject.toml
Labels: bug
